-- db/migrations/0002_driving_safety_bank.sql
-- Replaces the F1 placeholder bank with the CABA driving-safety bank:
-- 30 easy questions + 80 hard questions, four options each, 440 answer rows.
--
-- Why a new file instead of editing 0001: 0001 guards every insert with
-- WHERE NOT EXISTS (... e.question = v.question), matching on question TEXT.
-- Editing 0001 against the live database therefore does not update anything --
-- the new rows are simply not present, so the new text does not match, so they
-- get INSERTED ALONGSIDE the old ones. The database would settle at 10 easy
-- questions, 5 of them still F1, with duplicate question rows. Only a second
-- migration that clears the tables first makes a fresh database and the live
-- database converge on identical content.
--
-- Why answers are deleted before questions: the live foreign keys
-- easy_answers_relatedtoquestion_fkey and hard_answers_relatedtoquestion_fkey
-- are NO ACTION, not CASCADE, so Postgres rejects deleting a question that
-- still has answers. Order is mandatory.
--
-- Why the explicit BEGIN/COMMIT: db/apply.js sends each whole file through a
-- single pool.query(sql). The delete-all-then-insert here is destructive, so it
-- must be all-or-nothing; relying on the driver's implicit transaction for a
-- multi-statement simple query would make atomicity depend on driver behaviour.
--
-- DESTRUCTIVE, and approved: this drops the 7 easy + 5 hard questions, the 24 +
-- 20 answer rows, and the 42,420-byte photostring on the 'Test' row, including
-- the two smoke-test rows. Verified with the maintainer before this file was
-- written. Scoped to the public schema tables by name -- never a schema-wide
-- DROP, because this database also hosts the unrelated neon_auth schema.
--
-- Idempotency: re-running produces identical state. The blanket delete empties
-- the tables first, so the inserts always start from a known-empty set, and the
-- leading ordinal pins row order (see 0001 for why ORDER BY is load-bearing).

BEGIN;

-- ---------------------------------------------------------------------------
-- Clear existing data (answers first: FK is NO ACTION)
-- ---------------------------------------------------------------------------

DELETE FROM easy_answers;
DELETE FROM hard_answers;
DELETE FROM easy_questions;
DELETE FROM hard_questions;

-- Reset the sequences so ids restart at 1 and a fresh database and the live
-- database produce the same primary keys.

ALTER SEQUENCE easy_questions_ideasyquestion_seq RESTART WITH 1;
ALTER SEQUENCE easy_answers_ideasyanswer_seq RESTART WITH 1;
ALTER SEQUENCE hard_questions_idhardquestion_seq RESTART WITH 1;
ALTER SEQUENCE hard_answers_idhardanswer_seq RESTART WITH 1;

-- ---------------------------------------------------------------------------
-- Easy questions (30)
-- ---------------------------------------------------------------------------

INSERT INTO easy_questions (question, photostring)
SELECT v.question, NULL
FROM (VALUES
  (  1, '¿Qué indica la luz roja de un semáforo?'),
  (  2, '¿Qué significa un triángulo con borde rojo en la calzada?'),
  (  3, '¿Por qué se usa el cinturón de seguridad?'),
  (  4, '¿Por qué está prohibido usar el celular mientras se conduce?'),
  (  5, '¿Quién debe usar casco en un vehículo de dos ruedas?'),
  (  6, '¿Por dónde se cruza la calzada a pie?'),
  (  7, 'Tienes luz verde, pero hay una persona cruzando la calle. ¿Qué haces?'),
  (  8, '¿Qué conviene hacer con el auto que va adelante en el mismo carril?'),
  (  9, '¿Qué significa una línea continua pintada sobre la calzada?'),
  ( 10, '¿Qué hay que hacer al acercarse a una curva sin visibilidad?'),
  ( 11, '¿Qué significa la señalización de ''no estacionar'' en la calzada?'),
  ( 12, 'Antes de girar, ¿qué es correcto hacer?'),
  ( 13, '¿Cómo se debe sobrepasar una bicicleta?'),
  ( 14, '¿Para qué sirven las luces de giro?'),
  ( 15, '¿Qué conviene hacer cuando llueve?'),
  ( 16, '¿Qué hay que hacer si se levanta niebla en la ruta?'),
  ( 17, '¿Qué se hace si aparece un animal suelto en la calzada?'),
  ( 18, '¿Por qué es peligroso conducir con sueño?'),
  ( 19, '¿Qué conviene hacer antes de arrancar un viaje largo?'),
  ( 20, 'El semáforo cambia a amarillo mientras sigues detenido en la esquina. ¿Qué haces?'),
  ( 21, '¿Qué aviso da un vehículo con las balizas rojas intermitentes encendidas?'),
  ( 22, '¿Cuál es la edad mínima para obtener la licencia de conducir un automóvil?'),
  ( 23, '¿Hasta qué condición se exige usar un sistema de sujeción para niños?'),
  ( 24, '¿El airbag reemplaza al cinturón de seguridad?'),
  ( 25, '¿Para qué se usan las luces largas durante la noche?'),
  ( 26, '¿Por qué conviene mantener distancia de los autos estacionados?'),
  ( 27, 'En una rotonda, ¿quién tiene la prioridad?'),
  ( 28, 'Una persona cruza por la mitad de la calle sin respetar la senda. ¿Qué corresponde?'),
  ( 29, '¿Por qué no se debe pasar muy pegado a una bicicleta?'),
  ( 30, '¿Qué conviene hacer al descender del vehículo a la calzada?')
) AS v(ord, question)
ORDER BY v.ord;

INSERT INTO easy_answers (answer, iscorrect, relatedtoquestion)
SELECT v.answer, v.iscorrect, q.ideasyquestion
FROM (VALUES
  (  1, '¿Qué indica la luz roja de un semáforo?', 'Que se puede avanzar', FALSE),
  (  2, '¿Qué indica la luz roja de un semáforo?', 'Que hay que detenerse', TRUE),
  (  3, '¿Qué indica la luz roja de un semáforo?', 'Que se puede girar a la izquierda', FALSE),
  (  4, '¿Qué indica la luz roja de un semáforo?', 'Que la vía está libre', FALSE),
  (  5, '¿Qué significa un triángulo con borde rojo en la calzada?', 'Que hay un puesto de venta en el lugar', FALSE),
  (  6, '¿Qué significa un triángulo con borde rojo en la calzada?', 'Que la calle es de doble sentido', FALSE),
  (  7, '¿Qué significa un triángulo con borde rojo en la calzada?', 'Que hay que estar atento a un peligro', TRUE),
  (  8, '¿Qué significa un triángulo con borde rojo en la calzada?', 'Que termina la zona donde se permite el tránsito de vehículos', FALSE),
  (  9, '¿Por qué se usa el cinturón de seguridad?', 'Sólo para no molestar a los pasajeros', FALSE),
  ( 10, '¿Por qué se usa el cinturón de seguridad?', 'Porque frena el auto antes de un choque', FALSE),
  ( 11, '¿Por qué se usa el cinturón de seguridad?', 'Porque lo exige el seguro del auto', FALSE),
  ( 12, '¿Por qué se usa el cinturón de seguridad?', 'Para evitar salir despedido tras un choque', TRUE),
  ( 13, '¿Por qué está prohibido usar el celular mientras se conduce?', 'Porque consume batería', FALSE),
  ( 14, '¿Por qué está prohibido usar el celular mientras se conduce?', 'Porque se rompe el parabrisas', FALSE),
  ( 15, '¿Por qué está prohibido usar el celular mientras se conduce?', 'Porque todo conductor tiene un límite legal de mensajes', FALSE),
  ( 16, '¿Por qué está prohibido usar el celular mientras se conduce?', 'Porque distrae y aumenta el tiempo de reacción', TRUE),
  ( 17, '¿Quién debe usar casco en un vehículo de dos ruedas?', 'Todos los ocupantes', TRUE),
  ( 18, '¿Quién debe usar casco en un vehículo de dos ruedas?', 'Sólo quien conduce', FALSE),
  ( 19, '¿Quién debe usar casco en un vehículo de dos ruedas?', 'Sólo los menores de 18 años', FALSE),
  ( 20, '¿Quién debe usar casco en un vehículo de dos ruedas?', 'Sólo cuando llueve', FALSE),
  ( 21, '¿Por dónde se cruza la calzada a pie?', 'Por la senda peatonal o, si no hay, por las esquinas', TRUE),
  ( 22, '¿Por dónde se cruza la calzada a pie?', 'Por la mitad, donde se ve mejor', FALSE),
  ( 23, '¿Por dónde se cruza la calzada a pie?', 'Por la esquina más cercana', FALSE),
  ( 24, '¿Por dónde se cruza la calzada a pie?', 'Sólo cuando el semáforo está en rojo', FALSE),
  ( 25, 'Tienes luz verde, pero hay una persona cruzando la calle. ¿Qué haces?', 'Tocas la bocina y sigues', FALSE),
  ( 26, 'Tienes luz verde, pero hay una persona cruzando la calle. ¿Qué haces?', 'Frenas y esperas a que termine de cruzar', TRUE),
  ( 27, 'Tienes luz verde, pero hay una persona cruzando la calle. ¿Qué haces?', 'Pasas rápido para no demorar', FALSE),
  ( 28, 'Tienes luz verde, pero hay una persona cruzando la calle. ¿Qué haces?', 'Giras a la izquierda sin mirar', FALSE),
  ( 29, '¿Qué conviene hacer con el auto que va adelante en el mismo carril?', 'Pegarse a su parachoques para no perderlo de vista', FALSE),
  ( 30, '¿Qué conviene hacer con el auto que va adelante en el mismo carril?', 'Adelantarlo por la derecha', FALSE),
  ( 31, '¿Qué conviene hacer con el auto que va adelante en el mismo carril?', 'Pasar al carril izquierdo y seguir pegado', FALSE),
  ( 32, '¿Qué conviene hacer con el auto que va adelante en el mismo carril?', 'Mantener una distancia prudente', TRUE),
  ( 33, '¿Qué significa una línea continua pintada sobre la calzada?', 'Que se puede cambiar de carril con señalización', FALSE),
  ( 34, '¿Qué significa una línea continua pintada sobre la calzada?', 'Que la vía termina en ese punto', FALSE),
  ( 35, '¿Qué significa una línea continua pintada sobre la calzada?', 'Que no se puede sobrepasar ni cambiar de carril', TRUE),
  ( 36, '¿Qué significa una línea continua pintada sobre la calzada?', 'Que es un carril exclusivo para colectivos', FALSE),
  ( 37, '¿Qué hay que hacer al acercarse a una curva sin visibilidad?', 'Mantener la velocidad para no perder tiempo', FALSE),
  ( 38, '¿Qué hay que hacer al acercarse a una curva sin visibilidad?', 'Desacelerar antes de entrar', TRUE),
  ( 39, '¿Qué hay que hacer al acercarse a una curva sin visibilidad?', 'Tocar la bocina y acelerar', FALSE),
  ( 40, '¿Qué hay que hacer al acercarse a una curva sin visibilidad?', 'Cerrar las ventanas del vehículo', FALSE),
  ( 41, '¿Qué significa la señalización de ''no estacionar'' en la calzada?', 'Se puede estacionar por un rato corto', FALSE),
  ( 42, '¿Qué significa la señalización de ''no estacionar'' en la calzada?', 'Está prohibido estacionar en ese lugar', TRUE),
  ( 43, '¿Qué significa la señalización de ''no estacionar'' en la calzada?', 'Sólo se puede estacionar de noche', FALSE),
  ( 44, '¿Qué significa la señalización de ''no estacionar'' en la calzada?', 'Se puede estacionar pagando un importe', FALSE),
  ( 45, 'Antes de girar, ¿qué es correcto hacer?', 'Girar rápido sin mirar', FALSE),
  ( 46, 'Antes de girar, ¿qué es correcto hacer?', 'Tocar la bocina y girar', FALSE),
  ( 47, 'Antes de girar, ¿qué es correcto hacer?', 'Girar sólo si nadie te está mirando', FALSE),
  ( 48, 'Antes de girar, ¿qué es correcto hacer?', 'Mirar por el espejo, poner la luz de giro y reducir la velocidad', TRUE),
  ( 49, '¿Cómo se debe sobrepasar una bicicleta?', 'Pasando lo más cerca posible para no demorar', FALSE),
  ( 50, '¿Cómo se debe sobrepasar una bicicleta?', 'Tocando la bocina para avisar', FALSE),
  ( 51, '¿Cómo se debe sobrepasar una bicicleta?', 'Por la izquierda, dejando distancia lateral', TRUE),
  ( 52, '¿Cómo se debe sobrepasar una bicicleta?', 'Por la derecha, pegado al cordón', FALSE),
  ( 53, '¿Para qué sirven las luces de giro?', 'Para iluminar más el camino', FALSE),
  ( 54, '¿Para qué sirven las luces de giro?', 'Para avisar con antelación la maniobra que se va a hacer', TRUE),
  ( 55, '¿Para qué sirven las luces de giro?', 'Para indicar la velocidad del auto', FALSE),
  ( 56, '¿Para qué sirven las luces de giro?', 'Para distinguir a un vehículo averiado', FALSE),
  ( 57, '¿Qué conviene hacer cuando llueve?', 'Circular más rápido para no perder tiempo', FALSE),
  ( 58, '¿Qué conviene hacer cuando llueve?', 'Reducir la velocidad y aumentar la distancia de seguridad', TRUE),
  ( 59, '¿Qué conviene hacer cuando llueve?', 'Conducir con las luces largas encendidas', FALSE),
  ( 60, '¿Qué conviene hacer cuando llueve?', 'Frenar sólo cuando se vea el obstáculo', FALSE),
  ( 61, '¿Qué hay que hacer si se levanta niebla en la ruta?', 'Reducir la velocidad y no usar las luces largas', TRUE),
  ( 62, '¿Qué hay que hacer si se levanta niebla en la ruta?', 'Usar las luces largas a máxima potencia', FALSE),
  ( 63, '¿Qué hay que hacer si se levanta niebla en la ruta?', 'Detenerse en el mismo carril', FALSE),
  ( 64, '¿Qué hay que hacer si se levanta niebla en la ruta?', 'Aumentar la velocidad para avanzar antes de que se corte', FALSE),
  ( 65, '¿Qué se hace si aparece un animal suelto en la calzada?', 'Disminuir la velocidad, detenerse si hace falta y avisar a las autoridades', TRUE),
  ( 66, '¿Qué se hace si aparece un animal suelto en la calzada?', 'Tocar la bocina para espantarlo', FALSE),
  ( 67, '¿Qué se hace si aparece un animal suelto en la calzada?', 'Seguir a la misma velocidad', FALSE),
  ( 68, '¿Qué se hace si aparece un animal suelto en la calzada?', 'Girar bruscamente hacia el otro lado', FALSE),
  ( 69, '¿Por qué es peligroso conducir con sueño?', 'Porque el auto consume más combustible', FALSE),
  ( 70, '¿Por qué es peligroso conducir con sueño?', 'Porque se pierde capacidad de reacción y atención', TRUE),
  ( 71, '¿Por qué es peligroso conducir con sueño?', 'Porque se recalienta el motor', FALSE),
  ( 72, '¿Por qué es peligroso conducir con sueño?', 'Porque el seguro no cubre ese riesgo', FALSE),
  ( 73, '¿Qué conviene hacer antes de arrancar un viaje largo?', 'Dormir lo suficiente la noche anterior', TRUE),
  ( 74, '¿Qué conviene hacer antes de arrancar un viaje largo?', 'Tomar café bien caliente antes de salir', FALSE),
  ( 75, '¿Qué conviene hacer antes de arrancar un viaje largo?', 'Conducir de noche cuando hay menos tránsito', FALSE),
  ( 76, '¿Qué conviene hacer antes de arrancar un viaje largo?', 'Revisar sólo la apariencia exterior del auto', FALSE),
  ( 77, 'El semáforo cambia a amarillo mientras sigues detenido en la esquina. ¿Qué haces?', 'Arrancas rápido para pasar antes de que cambie', FALSE),
  ( 78, 'El semáforo cambia a amarillo mientras sigues detenido en la esquina. ¿Qué haces?', 'Giras a la izquierda sin esperar', FALSE),
  ( 79, 'El semáforo cambia a amarillo mientras sigues detenido en la esquina. ¿Qué haces?', 'Esperas a que cambie a verde', TRUE),
  ( 80, 'El semáforo cambia a amarillo mientras sigues detenido en la esquina. ¿Qué haces?', 'Cruzas igual porque la luz ya estaba verde', FALSE),
  ( 81, '¿Qué aviso da un vehículo con las balizas rojas intermitentes encendidas?', 'Que está circulando despacio por un tramo de riesgo', FALSE),
  ( 82, '¿Qué aviso da un vehículo con las balizas rojas intermitentes encendidas?', 'Que es un vehículo de transporte escolar', FALSE),
  ( 83, '¿Qué aviso da un vehículo con las balizas rojas intermitentes encendidas?', 'Que se acerca un vehículo de emergencia', FALSE),
  ( 84, '¿Qué aviso da un vehículo con las balizas rojas intermitentes encendidas?', 'Que está detenido o averiado', TRUE),
  ( 85, '¿Cuál es la edad mínima para obtener la licencia de conducir un automóvil?', '14 años', FALSE),
  ( 86, '¿Cuál es la edad mínima para obtener la licencia de conducir un automóvil?', '15 años', FALSE),
  ( 87, '¿Cuál es la edad mínima para obtener la licencia de conducir un automóvil?', '16 años', FALSE),
  ( 88, '¿Cuál es la edad mínima para obtener la licencia de conducir un automóvil?', '17 años', TRUE),
  ( 89, '¿Hasta qué condición se exige usar un sistema de sujeción para niños?', 'Hasta cumplir 6 años', FALSE),
  ( 90, '¿Hasta qué condición se exige usar un sistema de sujeción para niños?', 'Sólo hasta los 3 años', FALSE),
  ( 91, '¿Hasta qué condición se exige usar un sistema de sujeción para niños?', 'Hasta los 12 años, o menos de 1,50 m de estatura, o menos de 36 kg', TRUE),
  ( 92, '¿Hasta qué condición se exige usar un sistema de sujeción para niños?', 'Sólo cuando el niño viaja en el asiento delantero', FALSE),
  ( 93, '¿El airbag reemplaza al cinturón de seguridad?', 'Sí, porque es más eficaz', FALSE),
  ( 94, '¿El airbag reemplaza al cinturón de seguridad?', 'Sí, si el auto es nuevo', FALSE),
  ( 95, '¿El airbag reemplaza al cinturón de seguridad?', 'No, porque nunca se despliega', FALSE),
  ( 96, '¿El airbag reemplaza al cinturón de seguridad?', 'No: complementa al cinturón y no lo reemplaza', TRUE),
  ( 97, '¿Para qué se usan las luces largas durante la noche?', 'Para ver mejor cuando no hay tránsito cerca', TRUE),
  ( 98, '¿Para qué se usan las luces largas durante la noche?', 'Como señal de emergencia', FALSE),
  ( 99, '¿Para qué se usan las luces largas durante la noche?', 'Para avisar que se va a dar la vuelta', FALSE),
  (100, '¿Para qué se usan las luces largas durante la noche?', 'Para llamar la atención en un estacionamiento', FALSE),
  (101, '¿Por qué conviene mantener distancia de los autos estacionados?', 'Porque ocupan lugar', FALSE),
  (102, '¿Por qué conviene mantener distancia de los autos estacionados?', 'Porque pueden tener la alarma encendida', FALSE),
  (103, '¿Por qué conviene mantener distancia de los autos estacionados?', 'Porque una puerta puede abrirse de golpe', TRUE),
  (104, '¿Por qué conviene mantener distancia de los autos estacionados?', 'Porque están más fríos que los demás', FALSE),
  (105, 'En una rotonda, ¿quién tiene la prioridad?', 'El vehículo que ya está circulando dentro de la rotonda', TRUE),
  (106, 'En una rotonda, ¿quién tiene la prioridad?', 'El vehículo que va a entrar', FALSE),
  (107, 'En una rotonda, ¿quién tiene la prioridad?', 'El que llega más rápido', FALSE),
  (108, 'En una rotonda, ¿quién tiene la prioridad?', 'Siempre el que viene por la derecha', FALSE),
  (109, 'Una persona cruza por la mitad de la calle sin respetar la senda. ¿Qué corresponde?', 'Nada: la ley sólo obliga a la persona que cruza', FALSE),
  (110, 'Una persona cruza por la mitad de la calle sin respetar la senda. ¿Qué corresponde?', 'Esa persona es la única responsable del incidente', FALSE),
  (111, 'Una persona cruza por la mitad de la calle sin respetar la senda. ¿Qué corresponde?', 'Frenar y priorizar su integridad física', TRUE),
  (112, 'Una persona cruza por la mitad de la calle sin respetar la senda. ¿Qué corresponde?', 'Llamar a la policía de inmediato', FALSE),
  (113, '¿Por qué no se debe pasar muy pegado a una bicicleta?', 'Porque quien la conduce podría superar el límite de velocidad', FALSE),
  (114, '¿Por qué no se debe pasar muy pegado a una bicicleta?', 'Porque molesta a quien está en la bicicleta', FALSE),
  (115, '¿Por qué no se debe pasar muy pegado a una bicicleta?', 'Porque un contacto mínimo puede hacer que la bicicleta pierda equilibrio y caiga', TRUE),
  (116, '¿Por qué no se debe pasar muy pegado a una bicicleta?', 'Porque ocupa el mismo espacio que un automóvil', FALSE),
  (117, '¿Qué conviene hacer al descender del vehículo a la calzada?', 'Abrir la puerta de golpe para salir más rápido', FALSE),
  (118, '¿Qué conviene hacer al descender del vehículo a la calzada?', 'Encender las balizas y usar el chaleco reflectivo en vías rápidas', TRUE),
  (119, '¿Qué conviene hacer al descender del vehículo a la calzada?', 'Caminar por el medio del carril', FALSE),
  (120, '¿Qué conviene hacer al descender del vehículo a la calzada?', 'Esperar a que pase otro auto por la puerta abierta', FALSE)
) AS v(ord, question, answer, iscorrect)
JOIN easy_questions q ON q.question = v.question
ORDER BY v.ord;

-- ---------------------------------------------------------------------------
-- Hard questions (80)
-- ---------------------------------------------------------------------------

INSERT INTO hard_questions (question, photostring)
SELECT v.question, NULL
FROM (VALUES
  (  1, 'En una intersección sin semáforo, entre arterías de igual jerarquía, ¿quién tiene la prioridad?'),
  (  2, '¿Cuál es el orden de jerarquía entre tipos de arteria, de mayor a menor importancia?'),
  (  3, 'Frente a una señal de "Ceda el Paso", ¿qué diferencia hay con la señal de "Pare"?'),
  (  4, 'Al cruzar por nivel una vía férrea sin barrera en una intersección sin semáforo, ¿quién tiene la prioridad?'),
  (  5, '¿Dónde debe detenerse el vehículo ante la luz roja de un semáforo?'),
  (  6, '¿Qué indica un semáforo con luz roja intermitente?'),
  (  7, 'Con luz verde, ¿cuál de estas NO es una precaución válida antes de iniciar el cruce?'),
  (  8, 'Un vehículo estacionado quiere incorporarse a la circulación. ¿Cuándo tiene prioridad de paso?'),
  (  9, 'En una pendiente de ancho insuficiente para dos vehículos, ¿quién tiene la prioridad?'),
  ( 10, 'Entre una vía de tierra y una vía pavimentada que confluyen, ¿qué vehículo tiene la prioridad?'),
  ( 11, '¿A quién se debe facilitar el reingreso a la circulación?'),
  ( 12, 'Un vehículo de emergencia circula con las balizas encendidas pero sin sirena. ¿Tiene prioridad de paso?'),
  ( 13, 'Un cordón pintado de color amarillo en la calzada indica:'),
  ( 14, 'Un cordón pintado de color anaranjado indica:'),
  ( 15, 'Un reductor de velocidad consiste en:'),
  ( 16, 'Ante una contradicción entre normas y señales, ¿qué se respeta en primer lugar?'),
  ( 17, '¿Cuál es el límite máximo de velocidad en calles para un automóvil?'),
  ( 18, '¿Cuál es el límite máximo de velocidad en avenidas para un automóvil?'),
  ( 19, '¿Cuál es el límite máximo de velocidad en autopistas para un automóvil?'),
  ( 20, '¿Cuál es el límite máximo de velocidad en semiautopistas para un automóvil?'),
  ( 21, '¿Cuál es el límite máximo de velocidad en rutas para un automóvil?'),
  ( 22, '¿Cómo se fijan los límites mínimos de velocidad?'),
  ( 23, '¿Cuál es la distancia mínima de seguridad entre vehículos que indica la ley?'),
  ( 24, '¿Cuánto dura aproximadamente el tiempo de reacción de una persona que conduce?'),
  ( 25, 'La distancia de detención es la suma de:'),
  ( 26, '¿Qué es el "efecto túnel" al conducir?'),
  ( 27, '¿Cómo se debe proceder al encontrar un bache sobre la calzada?'),
  ( 28, 'Si el vehículo sale involuntariamente de la ruta, ¿qué corresponde hacer?'),
  ( 29, '¿Con qué antelación debe anticiparse una maniobra de giro?'),
  ( 30, '¿Cuál es el límite de velocidad en el Centro Peatonal?'),
  ( 31, '¿Cuál es la velocidad máxima permitida en las calles de convivencia?'),
  ( 32, 'Una persona que obtiene su licencia por primera vez, ¿qué restricción tiene durante los primeros 6 meses?'),
  ( 33, 'Si se conduce un automóvil con el cartel de principiante, ¿dónde debe exhibirse?'),
  ( 34, '¿Cuál es el límite de alcohol en sangre que se aplica a un conductor principiante?'),
  ( 35, '¿Cuál es el límite general de alcohol en sangre para conducir en CABA?'),
  ( 36, '¿Qué caracteriza a una autopista?'),
  ( 37, '¿Cuál es el límite de alcohol en sangre permitido para conducir una motocicleta?'),
  ( 38, 'Conducir con un nivel de alcohol igual o superior a 1,0 g/L es una conducta:'),
  ( 39, 'Si una persona se niega a realizarse la prueba de alcoholemia, la autoridad de control debe:'),
  ( 40, 'Una vez que se dejó de ingerir alcohol, ¿qué ocurre con la concentración en sangre durante la primera hora?'),
  ( 41, '¿Por qué se considera peligroso conducir con resaca?'),
  ( 42, '¿Qué efecto tiene permanecer despierto 17 horas al volante?'),
  ( 43, '¿Cada cuánto conviene interrumpir un viaje largo para descansar?'),
  ( 44, '¿Cuáles son los tres pasos que deben seguirse ante un siniestro vial?'),
  ( 45, '¿A qué distancia conviene colocar las balizas portátiles de un vehículo inmovilizado?'),
  ( 46, 'Un vehículo queda inmovilizado dentro de un túnel. ¿Qué corresponde hacer?'),
  ( 47, '¿A qué número se llama al servicio de Emergencias Médicas ante personas heridas?'),
  ( 48, 'Ante una persona lesionada, ¿cuándo está permitido moverla?'),
  ( 49, 'Una persona lesionada lleva casco puesto. ¿Qué debe hacerse?'),
  ( 50, 'Si una persona lesionada tiene un objeto clavado en el cuerpo, ¿qué corresponde?'),
  ( 51, '¿Cuál es la edad mínima para obtener la licencia de las categorías generales?'),
  ( 52, 'Si la licencia de conducir venció hace más de un año, ¿qué corresponde hacer?'),
  ( 53, '¿Con cuántos puntos se asigna el Scoring a quien obtiene su licencia por primera vez?'),
  ( 54, 'Si una persona llega a 0 puntos y es retenida en la vía pública, ¿qué documento recibe?'),
  ( 55, '¿Cómo se pueden recuperar voluntariamente 4 puntos del Scoring?'),
  ( 56, '¿De qué color era la cédula de identificación del automotor que identificaba al titular del vehículo?'),
  ( 57, '¿Cuándo corresponde la primera Verificación Técnica Vehicular de un automóvil particular radicado en CABA?'),
  ( 58, '¿Cuál es la vigencia de la VTV de un automóvil particular en los primeros años?'),
  ( 59, 'En una VTV con resultado "Condicional", ¿qué se debe hacer?'),
  ( 60, '¿Dónde se adhiere la oblea de la Verificación Técnica Vehicular?'),
  ( 61, '¿En qué plazo deben grabarse las autopartes de un vehículo radicado en CABA?'),
  ( 62, '¿En qué condiciones se considera detención a un vehículo inmóvil?'),
  ( 63, 'En una vía férrea sin barreras, ¿qué distancia mínima debe guardar la detención respecto de los rieles?'),
  ( 64, '¿En qué pasajes está prohibido estacionar?'),
  ( 65, '¿A qué distancia mínima de un paso ferroviario a nivel se puede estacionar?'),
  ( 66, '¿A qué distancia de la entrada de una escuela, en horario de clase, está prohibido estacionar?'),
  ( 67, '¿Cuánto tiempo puede permanecer un vehículo en un cajón azul?'),
  ( 68, 'Al guardar el equipaje en el baúl, ¿qué conviene hacer con las piezas más pesadas?'),
  ( 69, '¿En qué casos está permitida la marcha atrás en la Ciudad de Buenos Aires?'),
  ( 70, '¿Cuál es la función de los dibujos de un neumático en una calzada mojada?'),
  ( 71, '¿Cuántos años de antigüedad desde su fabricación es aceptable como máximo para un neumático?'),
  ( 72, '¿Qué efecto tiene tener los amortiguadores en mal estado sobre la frenada?'),
  ( 73, '¿Cuál es la función del sistema ABS?'),
  ( 74, '¿Quiénes deben usar cinturón de seguridad dentro de un automóvil?'),
  ( 75, '¿Cómo debe estar colocado el apoyacabeza?'),
  ( 76, '¿Qué debe usar un niño o una niña que viaje en un automóvil, según la normativa de CABA?'),
  ( 77, '¿Cuál es la distancia lateral mínima recomendada al sobrepasar un ciclista?'),
  ( 78, '¿Cuál es la potencia máxima del motor de un monopatín eléctrico?'),
  ( 79, '¿Cuál es la velocidad máxima de una bicicleta con asistencia eléctrica?'),
  ( 80, '¿Cuál es la edad mínima para conducir una bicicleta con asistencia eléctrica o un monopatín eléctrico?')
) AS v(ord, question)
ORDER BY v.ord;

INSERT INTO hard_answers (answer, iscorrect, relatedtoquestion)
SELECT v.answer, v.iscorrect, q.idhardquestion
FROM (VALUES
  (  1, 'En una intersección sin semáforo, entre arterías de igual jerarquía, ¿quién tiene la prioridad?', 'El vehículo de mayor porte', FALSE),
  (  2, 'En una intersección sin semáforo, entre arterías de igual jerarquía, ¿quién tiene la prioridad?', 'El que llega antes a la bocacalle', FALSE),
  (  3, 'En una intersección sin semáforo, entre arterías de igual jerarquía, ¿quién tiene la prioridad?', 'El que cruza por la derecha', TRUE),
  (  4, 'En una intersección sin semáforo, entre arterías de igual jerarquía, ¿quién tiene la prioridad?', 'El que transporta más pasajeros', FALSE),
  (  5, '¿Cuál es el orden de jerarquía entre tipos de arteria, de mayor a menor importancia?', 'Pasaje, calle, avenida', FALSE),
  (  6, '¿Cuál es el orden de jerarquía entre tipos de arteria, de mayor a menor importancia?', 'Avenida, calle, pasaje', TRUE),
  (  7, '¿Cuál es el orden de jerarquía entre tipos de arteria, de mayor a menor importancia?', 'Calle, avenida, pasaje', FALSE),
  (  8, '¿Cuál es el orden de jerarquía entre tipos de arteria, de mayor a menor importancia?', 'Avenida, pasaje, calle', FALSE),
  (  9, 'Frente a una señal de "Ceda el Paso", ¿qué diferencia hay con la señal de "Pare"?', 'Que solo se aplica en autopistas', FALSE),
  ( 10, 'Frente a una señal de "Ceda el Paso", ¿qué diferencia hay con la señal de "Pare"?', 'Que obliga a detenerse aunque no haya tráfico', FALSE),
  ( 11, 'Frente a una señal de "Ceda el Paso", ¿qué diferencia hay con la señal de "Pare"?', 'Que produce el mismo efecto que la señal de Pare', FALSE),
  ( 12, 'Frente a una señal de "Ceda el Paso", ¿qué diferencia hay con la señal de "Pare"?', 'Que la detención total no es obligatoria, salvo si facilita la circulación', TRUE),
  ( 13, 'Al cruzar por nivel una vía férrea sin barrera en una intersección sin semáforo, ¿quién tiene la prioridad?', 'El vehículo que viene del lado de la vía férrea', FALSE),
  ( 14, 'Al cruzar por nivel una vía férrea sin barrera en una intersección sin semáforo, ¿quién tiene la prioridad?', 'El que circula por la derecha', FALSE),
  ( 15, 'Al cruzar por nivel una vía férrea sin barrera en una intersección sin semáforo, ¿quién tiene la prioridad?', 'El que viene a mayor velocidad', FALSE),
  ( 16, 'Al cruzar por nivel una vía férrea sin barrera en una intersección sin semáforo, ¿quién tiene la prioridad?', 'El vehículo que sale del paso a nivel', TRUE),
  ( 17, '¿Dónde debe detenerse el vehículo ante la luz roja de un semáforo?', 'En el centro de la intersección', FALSE),
  ( 18, '¿Dónde debe detenerse el vehículo ante la luz roja de un semáforo?', 'Después de la línea de detención, sobre la calzada', FALSE),
  ( 19, '¿Dónde debe detenerse el vehículo ante la luz roja de un semáforo?', 'Donde mejor se vea el semáforo', FALSE),
  ( 20, '¿Dónde debe detenerse el vehículo ante la luz roja de un semáforo?', 'Antes de la senda peatonal o de la línea de detención', TRUE),
  ( 21, '¿Qué indica un semáforo con luz roja intermitente?', 'Que se puede avanzar con precaución', FALSE),
  ( 22, '¿Qué indica un semáforo con luz roja intermitente?', 'Que la vía está desobstruida', FALSE),
  ( 23, '¿Qué indica un semáforo con luz roja intermitente?', 'Que solo se puede girar a la izquierda', FALSE),
  ( 24, '¿Qué indica un semáforo con luz roja intermitente?', 'Que hay que detener la marcha antes de la encrucijada y retomarla cuando no exista riesgo de cruzar', TRUE),
  ( 25, 'Con luz verde, ¿cuál de estas NO es una precaución válida antes de iniciar el cruce?', 'Iniciar el cruce solo si hay espacio suficiente para ubicar el vehículo al otro lado', FALSE),
  ( 26, 'Con luz verde, ¿cuál de estas NO es una precaución válida antes de iniciar el cruce?', 'Permitir que termine de cruzar quien ya había iniciado el paso', FALSE),
  ( 27, 'Con luz verde, ¿cuál de estas NO es una precaución válida antes de iniciar el cruce?', 'Cruzar a máxima velocidad para no bloquear la vía', TRUE),
  ( 28, 'Con luz verde, ¿cuál de estas NO es una precaución válida antes de iniciar el cruce?', 'Verificar que no se obstruya la circulación transversal', FALSE),
  ( 29, 'Un vehículo estacionado quiere incorporarse a la circulación. ¿Cuándo tiene prioridad de paso?', 'Siempre, porque viene del cordón', FALSE),
  ( 30, 'Un vehículo estacionado quiere incorporarse a la circulación. ¿Cuándo tiene prioridad de paso?', 'Nunca, en ningún caso', FALSE),
  ( 31, 'Un vehículo estacionado quiere incorporarse a la circulación. ¿Cuándo tiene prioridad de paso?', 'Solo si se trata de un vehículo de emergencia', FALSE),
  ( 32, 'Un vehículo estacionado quiere incorporarse a la circulación. ¿Cuándo tiene prioridad de paso?', 'Solo si el tránsito se encuentra interrumpido por alguna razón', TRUE),
  ( 33, 'En una pendiente de ancho insuficiente para dos vehículos, ¿quién tiene la prioridad?', 'El que desciende, porque lo necesita con más urgencia', FALSE),
  ( 34, 'En una pendiente de ancho insuficiente para dos vehículos, ¿quién tiene la prioridad?', 'El que lleva carga', FALSE),
  ( 35, 'En una pendiente de ancho insuficiente para dos vehículos, ¿quién tiene la prioridad?', 'El último en llegar a la pendiente', FALSE),
  ( 36, 'En una pendiente de ancho insuficiente para dos vehículos, ¿quién tiene la prioridad?', 'El que asciende, por necesitar más tracción y tener menor campo visual', TRUE),
  ( 37, 'Entre una vía de tierra y una vía pavimentada que confluyen, ¿qué vehículo tiene la prioridad?', 'El que viene por la vía de tierra', FALSE),
  ( 38, 'Entre una vía de tierra y una vía pavimentada que confluyen, ¿qué vehículo tiene la prioridad?', 'El de mayor velocidad', FALSE),
  ( 39, 'Entre una vía de tierra y una vía pavimentada que confluyen, ¿qué vehículo tiene la prioridad?', 'El que llega último a la confluencia', FALSE),
  ( 40, 'Entre una vía de tierra y una vía pavimentada que confluyen, ¿qué vehículo tiene la prioridad?', 'El que circula por la vía pavimentada', TRUE),
  ( 41, '¿A quién se debe facilitar el reingreso a la circulación?', 'Al vehículo que realizó una maniobra de marcha atrás', FALSE),
  ( 42, '¿A quién se debe facilitar el reingreso a la circulación?', 'Al que transporta mayor cantidad de pasajeros', FALSE),
  ( 43, '¿A quién se debe facilitar el reingreso a la circulación?', 'Al que sale de un garaje', FALSE),
  ( 44, '¿A quién se debe facilitar el reingreso a la circulación?', 'Al colectivo que se detuvo en su parada', TRUE),
  ( 45, 'Un vehículo de emergencia circula con las balizas encendidas pero sin sirena. ¿Tiene prioridad de paso?', 'Sí, porque es un vehículo de emergencia', FALSE),
  ( 46, 'Un vehículo de emergencia circula con las balizas encendidas pero sin sirena. ¿Tiene prioridad de paso?', 'Sí, pero solo en autopistas', FALSE),
  ( 47, 'Un vehículo de emergencia circula con las balizas encendidas pero sin sirena. ¿Tiene prioridad de paso?', 'No, porque las balizas son para uso de vehículos particulares', FALSE),
  ( 48, 'Un vehículo de emergencia circula con las balizas encendidas pero sin sirena. ¿Tiene prioridad de paso?', 'No: con las balizas solamente está en servicio, pero no tiene prioridad de paso', TRUE),
  ( 49, 'Un cordón pintado de color amarillo en la calzada indica:', 'Prohibición de estacionar durante las 24 horas', TRUE),
  ( 50, 'Un cordón pintado de color amarillo en la calzada indica:', 'Parada obligatoria de colectivos', FALSE),
  ( 51, 'Un cordón pintado de color amarillo en la calzada indica:', 'Carga y descarga de mercaderías', FALSE),
  ( 52, 'Un cordón pintado de color amarillo en la calzada indica:', 'Estacionamiento exclusivo de ciclorodados y motovehículos', FALSE),
  ( 53, 'Un cordón pintado de color anaranjado indica:', 'Prohibición de detener el vehículo', FALSE),
  ( 54, 'Un cordón pintado de color anaranjado indica:', 'Paso obligatorio de peatones', FALSE),
  ( 55, 'Un cordón pintado de color anaranjado indica:', 'Estacionamiento reservado a taxis y remises', FALSE),
  ( 56, 'Un cordón pintado de color anaranjado indica:', 'Estacionamiento exclusivo de ciclorodados y motovehículos', TRUE),
  ( 57, 'Un reductor de velocidad consiste en:', 'Un badén delimitado con pintura amarilla', FALSE),
  ( 58, 'Un reductor de velocidad consiste en:', 'Una serie de conos naranjas sobre la calzada', FALSE),
  ( 59, 'Un reductor de velocidad consiste en:', 'Una diferencia de rasante de 10 cm con señalización preventiva', FALSE),
  ( 60, 'Un reductor de velocidad consiste en:', 'Un dispositivo que disminuye el ancho del carril hasta una dimensión no menor a 2,80 m e induce a reducir la velocidad', TRUE),
  ( 61, 'Ante una contradicción entre normas y señales, ¿qué se respeta en primer lugar?', 'La señalización de la vía', FALSE),
  ( 62, 'Ante una contradicción entre normas y señales, ¿qué se respeta en primer lugar?', 'El criterio de quien conduce', FALSE),
  ( 63, 'Ante una contradicción entre normas y señales, ¿qué se respeta en primer lugar?', 'La costumbre del barrio', FALSE),
  ( 64, 'Ante una contradicción entre normas y señales, ¿qué se respeta en primer lugar?', 'Las indicaciones de los agentes de tránsito y de la autoridad de control', TRUE),
  ( 65, '¿Cuál es el límite máximo de velocidad en calles para un automóvil?', '60 km/h', FALSE),
  ( 66, '¿Cuál es el límite máximo de velocidad en calles para un automóvil?', '40 km/h', TRUE),
  ( 67, '¿Cuál es el límite máximo de velocidad en calles para un automóvil?', '80 km/h', FALSE),
  ( 68, '¿Cuál es el límite máximo de velocidad en calles para un automóvil?', '110 km/h', FALSE),
  ( 69, '¿Cuál es el límite máximo de velocidad en avenidas para un automóvil?', '40 km/h', FALSE),
  ( 70, '¿Cuál es el límite máximo de velocidad en avenidas para un automóvil?', '80 km/h', FALSE),
  ( 71, '¿Cuál es el límite máximo de velocidad en avenidas para un automóvil?', '60 km/h', TRUE),
  ( 72, '¿Cuál es el límite máximo de velocidad en avenidas para un automóvil?', '100 km/h', FALSE),
  ( 73, '¿Cuál es el límite máximo de velocidad en autopistas para un automóvil?', '120 km/h', FALSE),
  ( 74, '¿Cuál es el límite máximo de velocidad en autopistas para un automóvil?', '100 km/h', TRUE),
  ( 75, '¿Cuál es el límite máximo de velocidad en autopistas para un automóvil?', '80 km/h', FALSE),
  ( 76, '¿Cuál es el límite máximo de velocidad en autopistas para un automóvil?', '60 km/h', FALSE),
  ( 77, '¿Cuál es el límite máximo de velocidad en semiautopistas para un automóvil?', '120 km/h', TRUE),
  ( 78, '¿Cuál es el límite máximo de velocidad en semiautopistas para un automóvil?', '80 km/h', FALSE),
  ( 79, '¿Cuál es el límite máximo de velocidad en semiautopistas para un automóvil?', '100 km/h', FALSE),
  ( 80, '¿Cuál es el límite máximo de velocidad en semiautopistas para un automóvil?', '60 km/h', FALSE),
  ( 81, '¿Cuál es el límite máximo de velocidad en rutas para un automóvil?', '100 km/h', FALSE),
  ( 82, '¿Cuál es el límite máximo de velocidad en rutas para un automóvil?', '60 km/h', FALSE),
  ( 83, '¿Cuál es el límite máximo de velocidad en rutas para un automóvil?', '120 km/h', FALSE),
  ( 84, '¿Cuál es el límite máximo de velocidad en rutas para un automóvil?', '110 km/h', TRUE),
  ( 85, '¿Cómo se fijan los límites mínimos de velocidad?', 'A la mitad de los límites máximos de cada tipo de arteria', TRUE),
  ( 86, '¿Cómo se fijan los límites mínimos de velocidad?', 'Deben ser iguales a los máximos', FALSE),
  ( 87, '¿Cómo se fijan los límites mínimos de velocidad?', 'A un tercio de los límites máximos', FALSE),
  ( 88, '¿Cómo se fijan los límites mínimos de velocidad?', 'Solo existen en autopistas', FALSE),
  ( 89, '¿Cuál es la distancia mínima de seguridad entre vehículos que indica la ley?', '1 segundo', FALSE),
  ( 90, '¿Cuál es la distancia mínima de seguridad entre vehículos que indica la ley?', '2 segundos', TRUE),
  ( 91, '¿Cuál es la distancia mínima de seguridad entre vehículos que indica la ley?', '3 segundos', FALSE),
  ( 92, '¿Cuál es la distancia mínima de seguridad entre vehículos que indica la ley?', '5 segundos', FALSE),
  ( 93, '¿Cuánto dura aproximadamente el tiempo de reacción de una persona que conduce?', '1 segundo', TRUE),
  ( 94, '¿Cuánto dura aproximadamente el tiempo de reacción de una persona que conduce?', '2 segundos', FALSE),
  ( 95, '¿Cuánto dura aproximadamente el tiempo de reacción de una persona que conduce?', 'Medio segundo', FALSE),
  ( 96, '¿Cuánto dura aproximadamente el tiempo de reacción de una persona que conduce?', '4 segundos', FALSE),
  ( 97, 'La distancia de detención es la suma de:', 'Distancia de reacción y distancia de frenado', TRUE),
  ( 98, 'La distancia de detención es la suma de:', 'Distancia de frenado y espacio lateral', FALSE),
  ( 99, 'La distancia de detención es la suma de:', 'Distancia de reacción y longitud del vehículo', FALSE),
  (100, 'La distancia de detención es la suma de:', 'Espacio libre y distancia de frenado', FALSE),
  (101, '¿Qué es el "efecto túnel" al conducir?', 'La pérdida de visión periférica por circular a alta velocidad', TRUE),
  (102, '¿Qué es el "efecto túnel" al conducir?', 'La pérdida de la audición por el ruido del motor', FALSE),
  (103, '¿Qué es el "efecto túnel" al conducir?', 'El retraso en la frenada por temperatura del freno', FALSE),
  (104, '¿Qué es el "efecto túnel" al conducir?', 'La desorientación al salir de un túnel', FALSE),
  (105, '¿Cómo se debe proceder al encontrar un bache sobre la calzada?', 'Aumentar la velocidad para atravesarlo antes de tiempo', FALSE),
  (106, '¿Cómo se debe proceder al encontrar un bache sobre la calzada?', 'Disminuir la velocidad y aumentar la distancia de seguridad con el vehículo de adelante', TRUE),
  (107, '¿Cómo se debe proceder al encontrar un bache sobre la calzada?', 'Mantener la velocidad para no perder el ritmo del tránsito', FALSE),
  (108, '¿Cómo se debe proceder al encontrar un bache sobre la calzada?', 'Frenar solo después de pasar el bache', FALSE),
  (109, 'Si el vehículo sale involuntariamente de la ruta, ¿qué corresponde hacer?', 'Desacelerar sin tratar de volver a la calzada dando volantazos', TRUE),
  (110, 'Si el vehículo sale involuntariamente de la ruta, ¿qué corresponde hacer?', 'Realizar una maniobra brusca de dirección para reencauzar el vehículo', FALSE),
  (111, 'Si el vehículo sale involuntariamente de la ruta, ¿qué corresponde hacer?', 'Mantener la velocidad hasta recuperar la trayectoria', FALSE),
  (112, 'Si el vehículo sale involuntariamente de la ruta, ¿qué corresponde hacer?', 'Frenar en seco y esperar asistencia en el lugar', FALSE),
  (113, '¿Con qué antelación debe anticiparse una maniobra de giro?', 'Con la luz de giro unos 10 metros antes', FALSE),
  (114, '¿Con qué antelación debe anticiparse una maniobra de giro?', 'Sin señalización previa', FALSE),
  (115, '¿Con qué antelación debe anticiparse una maniobra de giro?', 'Con la luz de giro unos 30 metros antes', TRUE),
  (116, '¿Con qué antelación debe anticiparse una maniobra de giro?', 'Solo al llegar a la esquina', FALSE),
  (117, '¿Cuál es el límite de velocidad en el Centro Peatonal?', '10 km/h', TRUE),
  (118, '¿Cuál es el límite de velocidad en el Centro Peatonal?', '20 km/h', FALSE),
  (119, '¿Cuál es el límite de velocidad en el Centro Peatonal?', '30 km/h', FALSE),
  (120, '¿Cuál es el límite de velocidad en el Centro Peatonal?', '40 km/h', FALSE),
  (121, '¿Cuál es la velocidad máxima permitida en las calles de convivencia?', '10 km/h', FALSE),
  (122, '¿Cuál es la velocidad máxima permitida en las calles de convivencia?', '20 km/h', TRUE),
  (123, '¿Cuál es la velocidad máxima permitida en las calles de convivencia?', '40 km/h', FALSE),
  (124, '¿Cuál es la velocidad máxima permitida en las calles de convivencia?', '60 km/h', FALSE),
  (125, 'Una persona que obtiene su licencia por primera vez, ¿qué restricción tiene durante los primeros 6 meses?', 'No puede conducir si llueve', FALSE),
  (126, 'Una persona que obtiene su licencia por primera vez, ¿qué restricción tiene durante los primeros 6 meses?', 'No puede circular por arterias donde se permitan velocidades superiores a 70 km/h', TRUE),
  (127, 'Una persona que obtiene su licencia por primera vez, ¿qué restricción tiene durante los primeros 6 meses?', 'No puede conducir después de las 20 horas', FALSE),
  (128, 'Una persona que obtiene su licencia por primera vez, ¿qué restricción tiene durante los primeros 6 meses?', 'No puede utilizar el cambio manual', FALSE),
  (129, 'Si se conduce un automóvil con el cartel de principiante, ¿dónde debe exhibirse?', 'En el techo del vehículo', FALSE),
  (130, 'Si se conduce un automóvil con el cartel de principiante, ¿dónde debe exhibirse?', 'En la parte inferior del parabrisas y en la luneta', TRUE),
  (131, 'Si se conduce un automóvil con el cartel de principiante, ¿dónde debe exhibirse?', 'Dentro de la guantera', FALSE),
  (132, 'Si se conduce un automóvil con el cartel de principiante, ¿dónde debe exhibirse?', 'Solo en el interior del baúl', FALSE),
  (133, '¿Cuál es el límite de alcohol en sangre que se aplica a un conductor principiante?', '0,5 g/L durante los primeros 6 meses', FALSE),
  (134, '¿Cuál es el límite de alcohol en sangre que se aplica a un conductor principiante?', '0,2 g/L durante el primer año', FALSE),
  (135, '¿Cuál es el límite de alcohol en sangre que se aplica a un conductor principiante?', '0,0 g/L durante los dos años de condición principiante', TRUE),
  (136, '¿Cuál es el límite de alcohol en sangre que se aplica a un conductor principiante?', '0,5 g/L durante toda la vida de la licencia', FALSE),
  (137, '¿Cuál es el límite general de alcohol en sangre para conducir en CABA?', '1,0 g/L', FALSE),
  (138, '¿Cuál es el límite general de alcohol en sangre para conducir en CABA?', '0,5 g/L', TRUE),
  (139, '¿Cuál es el límite general de alcohol en sangre para conducir en CABA?', '0,2 g/L', FALSE),
  (140, '¿Cuál es el límite general de alcohol en sangre para conducir en CABA?', '0,0 g/L', FALSE),
  (141, '¿Qué caracteriza a una autopista?', 'Tiene cruces a nivel y semáforos frecuentes', FALSE),
  (142, '¿Qué caracteriza a una autopista?', 'No tiene cruces a nivel y sus accesos están controlados', TRUE),
  (143, '¿Qué caracteriza a una autopista?', 'Es de un solo carril por sentido', FALSE),
  (144, '¿Qué caracteriza a una autopista?', 'Sólo se usa para el transporte de mercancías', FALSE),
  (145, '¿Cuál es el límite de alcohol en sangre permitido para conducir una motocicleta?', '0,0 g/L', FALSE),
  (146, '¿Cuál es el límite de alcohol en sangre permitido para conducir una motocicleta?', '0,5 g/L', FALSE),
  (147, '¿Cuál es el límite de alcohol en sangre permitido para conducir una motocicleta?', '0,2 g/L', TRUE),
  (148, '¿Cuál es el límite de alcohol en sangre permitido para conducir una motocicleta?', '0,8 g/L', FALSE),
  (149, 'Conducir con un nivel de alcohol igual o superior a 1,0 g/L es una conducta:', 'Administrativamente correcta si no hubo incidentes', FALSE),
  (150, 'Conducir con un nivel de alcohol igual o superior a 1,0 g/L es una conducta:', 'Contravencional, aun sin que haya producido daños', TRUE),
  (151, 'Conducir con un nivel de alcohol igual o superior a 1,0 g/L es una conducta:', 'Una falta de tránsito sin sanción', FALSE),
  (152, 'Conducir con un nivel de alcohol igual o superior a 1,0 g/L es una conducta:', 'Permitida si se conduce con un acompañante sobrio', FALSE),
  (153, 'Si una persona se niega a realizarse la prueba de alcoholemia, la autoridad de control debe:', 'Dejar que continúe conduciendo si no hay antecedentes', FALSE),
  (154, 'Si una persona se niega a realizarse la prueba de alcoholemia, la autoridad de control debe:', 'Advertirle solo por escrito y dejarlo pasar', FALSE),
  (155, 'Si una persona se niega a realizarse la prueba de alcoholemia, la autoridad de control debe:', 'Prohibirle continuar conduciendo y ordenar la remoción del vehículo, presumiendo alcoholemia positiva', TRUE),
  (156, 'Si una persona se niega a realizarse la prueba de alcoholemia, la autoridad de control debe:', 'Aplicarle una multa automática en el acto', FALSE),
  (157, 'Una vez que se dejó de ingerir alcohol, ¿qué ocurre con la concentración en sangre durante la primera hora?', 'Baja inmediatamente a cero', FALSE),
  (158, 'Una vez que se dejó de ingerir alcohol, ¿qué ocurre con la concentración en sangre durante la primera hora?', 'Baja a la mitad en los primeros diez minutos', FALSE),
  (159, 'Una vez que se dejó de ingerir alcohol, ¿qué ocurre con la concentración en sangre durante la primera hora?', 'Continúa subiendo durante aproximadamente la primera hora', TRUE),
  (160, 'Una vez que se dejó de ingerir alcohol, ¿qué ocurre con la concentración en sangre durante la primera hora?', 'Se mantiene constante durante toda la noche', FALSE),
  (161, '¿Por qué se considera peligroso conducir con resaca?', 'Porque altera la coordinación, la atención y el tiempo de reacción, y se equipara a conducir alcoholizado', TRUE),
  (162, '¿Por qué se considera peligroso conducir con resaca?', 'Porque el cuerpo se deshidrata y falla la visión', FALSE),
  (163, '¿Por qué se considera peligroso conducir con resaca?', 'Porque el seguro no cubre los daños', FALSE),
  (164, '¿Por qué se considera peligroso conducir con resaca?', 'Porque la caldera del auto puede sobrecalentarse', FALSE),
  (165, '¿Qué efecto tiene permanecer despierto 17 horas al volante?', 'Un aumento de la visión periférica', FALSE),
  (166, '¿Qué efecto tiene permanecer despierto 17 horas al volante?', 'El mismo nivel de reacción que una persona con alcohol en sangre por encima del permitido', TRUE),
  (167, '¿Qué efecto tiene permanecer despierto 17 horas al volante?', 'Una reducción del tiempo de frenado', FALSE),
  (168, '¿Qué efecto tiene permanecer despierto 17 horas al volante?', 'Ninguno, si se condujo con regularidad', FALSE),
  (169, '¿Cada cuánto conviene interrumpir un viaje largo para descansar?', 'Cada 200 kilómetros o cada dos horas; en motovehículos, cada 100 kilómetros o cada hora', TRUE),
  (170, '¿Cada cuánto conviene interrumpir un viaje largo para descansar?', 'Solo cada 500 kilómetros', FALSE),
  (171, '¿Cada cuánto conviene interrumpir un viaje largo para descansar?', 'Solo al llegar al destino', FALSE),
  (172, '¿Cada cuánto conviene interrumpir un viaje largo para descansar?', 'Cada 30 minutos, sin importar la distancia', FALSE),
  (173, '¿Cuáles son los tres pasos que deben seguirse ante un siniestro vial?', 'Detenerse - Alertar - Esperar', FALSE),
  (174, '¿Cuáles son los tres pasos que deben seguirse ante un siniestro vial?', 'Proteger - Alertar - Socorrer', TRUE),
  (175, '¿Cuáles son los tres pasos que deben seguirse ante un siniestro vial?', 'Llamar - Consultar - Reparar', FALSE),
  (176, '¿Cuáles son los tres pasos que deben seguirse ante un siniestro vial?', 'Fotografiar - Mover - Avisar', FALSE),
  (177, '¿A qué distancia conviene colocar las balizas portátiles de un vehículo inmovilizado?', 'En ciudad, a 30 y 60 metros; en ruta, al menos a 50 y 100 metros', TRUE),
  (178, '¿A qué distancia conviene colocar las balizas portátiles de un vehículo inmovilizado?', 'Siempre a 10 y 20 metros, en cualquier vía', FALSE),
  (179, '¿A qué distancia conviene colocar las balizas portátiles de un vehículo inmovilizado?', 'Solo a 5 metros del vehículo', FALSE),
  (180, '¿A qué distancia conviene colocar las balizas portátiles de un vehículo inmovilizado?', 'A 200 metros del vehículo, en autopistas', FALSE),
  (181, 'Un vehículo queda inmovilizado dentro de un túnel. ¿Qué corresponde hacer?', 'Dejar las balizas encendidas y esperar adentro del auto', FALSE),
  (182, 'Un vehículo queda inmovilizado dentro de un túnel. ¿Qué corresponde hacer?', 'Mantener luces de posición y balizas, apagar el motor y abandonar el vehículo usando el chaleco reflectante', TRUE),
  (183, 'Un vehículo queda inmovilizado dentro de un túnel. ¿Qué corresponde hacer?', 'Encender solo las luces largas y permanecer sentado', FALSE),
  (184, 'Un vehículo queda inmovilizado dentro de un túnel. ¿Qué corresponde hacer?', 'Caminar por el arcén hasta la salida a pie', FALSE),
  (185, '¿A qué número se llama al servicio de Emergencias Médicas ante personas heridas?', '911 y luego 107', FALSE),
  (186, '¿A qué número se llama al servicio de Emergencias Médicas ante personas heridas?', '147 y luego 911', FALSE),
  (187, '¿A qué número se llama al servicio de Emergencias Médicas ante personas heridas?', '107 y luego 911', TRUE),
  (188, '¿A qué número se llama al servicio de Emergencias Médicas ante personas heridas?', '0800-222-3425', FALSE),
  (189, 'Ante una persona lesionada, ¿cuándo está permitido moverla?', 'Nunca, bajo ninguna circunstancia', FALSE),
  (190, 'Ante una persona lesionada, ¿cuándo está permitido moverla?', 'Cuando exista posibilidad de atropello o por una necesidad médica', TRUE),
  (191, 'Ante una persona lesionada, ¿cuándo está permitido moverla?', 'Siempre, para llevarla a un lugar seguro', FALSE),
  (192, 'Ante una persona lesionada, ¿cuándo está permitido moverla?', 'Solo si la persona está inconsciente', FALSE),
  (193, 'Una persona lesionada lleva casco puesto. ¿Qué debe hacerse?', 'Retirarlo de inmediato para liberar la cabeza', FALSE),
  (194, 'Una persona lesionada lleva casco puesto. ¿Qué debe hacerse?', 'No retirarlo, salvo que haya vómito o asfixia', TRUE),
  (195, 'Una persona lesionada lleva casco puesto. ¿Qué debe hacerse?', 'Retirarlo solo si la persona se queja de dolor', FALSE),
  (196, 'Una persona lesionada lleva casco puesto. ¿Qué debe hacerse?', 'Retirarlo una vez trasladada al lugar de la cabecera', FALSE),
  (197, 'Si una persona lesionada tiene un objeto clavado en el cuerpo, ¿qué corresponde?', 'Retirarlo para limpiar la herida', FALSE),
  (198, 'Si una persona lesionada tiene un objeto clavado en el cuerpo, ¿qué corresponde?', 'No retirarlo, para no provocar una hemorragia', TRUE),
  (199, 'Si una persona lesionada tiene un objeto clavado en el cuerpo, ¿qué corresponde?', 'Cortarlo con un cuchillo para liberarla', FALSE),
  (200, 'Si una persona lesionada tiene un objeto clavado en el cuerpo, ¿qué corresponde?', 'Moverlo y revisar si hay hemorragia', FALSE),
  (201, '¿Cuál es la edad mínima para obtener la licencia de las categorías generales?', '16 años para ciclomotores, 17 años para las restantes categorías y 21 años para conductores profesionales', TRUE),
  (202, '¿Cuál es la edad mínima para obtener la licencia de las categorías generales?', '18 años en todos los casos', FALSE),
  (203, '¿Cuál es la edad mínima para obtener la licencia de las categorías generales?', '16 años en todos los casos', FALSE),
  (204, '¿Cuál es la edad mínima para obtener la licencia de las categorías generales?', '21 años en todos los casos', FALSE),
  (205, 'Si la licencia de conducir venció hace más de un año, ¿qué corresponde hacer?', 'Renovarla pagando una tasa', FALSE),
  (206, 'Si la licencia de conducir venció hace más de un año, ¿qué corresponde hacer?', 'Circular con una autorización transitoria', FALSE),
  (207, 'Si la licencia de conducir venció hace más de un año, ¿qué corresponde hacer?', 'Usarla hasta la próxima renovación obligatoria', FALSE),
  (208, 'Si la licencia de conducir venció hace más de un año, ¿qué corresponde hacer?', 'Tramitar un nuevo otorgamiento, como si fuera nueva', TRUE),
  (209, '¿Con cuántos puntos se asigna el Scoring a quien obtiene su licencia por primera vez?', '10 puntos', FALSE),
  (210, '¿Con cuántos puntos se asigna el Scoring a quien obtiene su licencia por primera vez?', '20 puntos', TRUE),
  (211, '¿Con cuántos puntos se asigna el Scoring a quien obtiene su licencia por primera vez?', '15 puntos', FALSE),
  (212, '¿Con cuántos puntos se asigna el Scoring a quien obtiene su licencia por primera vez?', '25 puntos', FALSE),
  (213, 'Si una persona llega a 0 puntos y es retenida en la vía pública, ¿qué documento recibe?', 'Una boleta de citación que la habilita a conducir por un plazo máximo de 3 días hábiles', TRUE),
  (214, 'Si una persona llega a 0 puntos y es retenida en la vía pública, ¿qué documento recibe?', 'Una licencia especial por 30 días', FALSE),
  (215, 'Si una persona llega a 0 puntos y es retenida en la vía pública, ¿qué documento recibe?', 'Una multa a pagar en el acto', FALSE),
  (216, 'Si una persona llega a 0 puntos y es retenida en la vía pública, ¿qué documento recibe?', 'Una copia de la licencia vencida', FALSE),
  (217, '¿Cómo se pueden recuperar voluntariamente 4 puntos del Scoring?', 'Aprobando un curso especializado de educación vial, una sola vez por año', TRUE),
  (218, '¿Cómo se pueden recuperar voluntariamente 4 puntos del Scoring?', 'Pagando una multa en el acto', FALSE),
  (219, '¿Cómo se pueden recuperar voluntariamente 4 puntos del Scoring?', 'Con un examen médico renovatorio', FALSE),
  (220, '¿Cómo se pueden recuperar voluntariamente 4 puntos del Scoring?', 'Presentando un reclamo administrativo', FALSE),
  (221, '¿De qué color era la cédula de identificación del automotor que identificaba al titular del vehículo?', 'Verde', TRUE),
  (222, '¿De qué color era la cédula de identificación del automotor que identificaba al titular del vehículo?', 'Marrón', FALSE),
  (223, '¿De qué color era la cédula de identificación del automotor que identificaba al titular del vehículo?', 'Azul', FALSE),
  (224, '¿De qué color era la cédula de identificación del automotor que identificaba al titular del vehículo?', 'Rosa', FALSE),
  (225, '¿Cuándo corresponde la primera Verificación Técnica Vehicular de un automóvil particular radicado en CABA?', 'Al cumplir el primer año de antigüedad', FALSE),
  (226, '¿Cuándo corresponde la primera Verificación Técnica Vehicular de un automóvil particular radicado en CABA?', 'A los 100.000 kilómetros', FALSE),
  (227, '¿Cuándo corresponde la primera Verificación Técnica Vehicular de un automóvil particular radicado en CABA?', 'A partir del cuarto año de antigüedad cumplido, o a los 60.000 kilómetros', TRUE),
  (228, '¿Cuándo corresponde la primera Verificación Técnica Vehicular de un automóvil particular radicado en CABA?', 'Solo cuando cambia de propietario', FALSE),
  (229, '¿Cuál es la vigencia de la VTV de un automóvil particular en los primeros años?', 'Un año', FALSE),
  (230, '¿Cuál es la vigencia de la VTV de un automóvil particular en los primeros años?', 'Seis meses', FALSE),
  (231, '¿Cuál es la vigencia de la VTV de un automóvil particular en los primeros años?', 'Dos años, hasta el octavo año de antigüedad o los 80.000 kilómetros', TRUE),
  (232, '¿Cuál es la vigencia de la VTV de un automóvil particular en los primeros años?', 'Cinco años', FALSE),
  (233, 'En una VTV con resultado "Condicional", ¿qué se debe hacer?', 'Resolver los defectos leves en un plazo de 60 días hábiles y volver a verificar sin cargo; el vehículo puede circular', TRUE),
  (234, 'En una VTV con resultado "Condicional", ¿qué se debe hacer?', 'Retirar el vehículo de la vía pública de inmediato', FALSE),
  (235, 'En una VTV con resultado "Condicional", ¿qué se debe hacer?', 'Repetir la VTV hasta obtener el resultado "Apto"', FALSE),
  (236, 'En una VTV con resultado "Condicional", ¿qué se debe hacer?', 'Solicitar una VTV en otra jurisdicción', FALSE),
  (237, '¿Dónde se adhiere la oblea de la Verificación Técnica Vehicular?', 'En el interior del vehículo, junto a la documentación', FALSE),
  (238, '¿Dónde se adhiere la oblea de la Verificación Técnica Vehicular?', 'En el tablero, del lado de quien conduce', FALSE),
  (239, '¿Dónde se adhiere la oblea de la Verificación Técnica Vehicular?', 'Al vidrio parabrisas; en el caso de los motovehículos, al dorso del certificado', TRUE),
  (240, '¿Dónde se adhiere la oblea de la Verificación Técnica Vehicular?', 'En el buzón del propietario', FALSE),
  (241, '¿En qué plazo deben grabarse las autopartes de un vehículo radicado en CABA?', 'Dentro de los 30 días de patentamiento', TRUE),
  (242, '¿En qué plazo deben grabarse las autopartes de un vehículo radicado en CABA?', 'Dentro del primer año de antigüedad', FALSE),
  (243, '¿En qué plazo deben grabarse las autopartes de un vehículo radicado en CABA?', 'En cada Verificación Técnica Vehicular', FALSE),
  (244, '¿En qué plazo deben grabarse las autopartes de un vehículo radicado en CABA?', 'Solo si el vehículo es sustituido', FALSE),
  (245, '¿En qué condiciones se considera detención a un vehículo inmóvil?', 'Cualquier vehículo detenido más de 5 minutos', FALSE),
  (246, '¿En qué condiciones se considera detención a un vehículo inmóvil?', 'Cuando permanece sin movimiento hasta 2 minutos, sin que la persona que conduce abandone el vehículo', TRUE),
  (247, '¿En qué condiciones se considera detención a un vehículo inmóvil?', 'Solo cuando tiene las balizas encendidas junto a la acera', FALSE),
  (248, '¿En qué condiciones se considera detención a un vehículo inmóvil?', 'Cuando el motor está encendido y el vehículo no avanza', FALSE),
  (249, 'En una vía férrea sin barreras, ¿qué distancia mínima debe guardar la detención respecto de los rieles?', '2 metros', FALSE),
  (250, 'En una vía férrea sin barreras, ¿qué distancia mínima debe guardar la detención respecto de los rieles?', '10 metros', FALSE),
  (251, 'En una vía férrea sin barreras, ¿qué distancia mínima debe guardar la detención respecto de los rieles?', '3 metros', FALSE),
  (252, 'En una vía férrea sin barreras, ¿qué distancia mínima debe guardar la detención respecto de los rieles?', '5 metros', TRUE),
  (253, '¿En qué pasajes está prohibido estacionar?', 'En los de menos de 4,5 metros de ancho', TRUE),
  (254, '¿En qué pasajes está prohibido estacionar?', 'En los de menos de 5 metros de ancho', FALSE),
  (255, '¿En qué pasajes está prohibido estacionar?', 'En los de menos de 6 metros de ancho', FALSE),
  (256, '¿En qué pasajes está prohibido estacionar?', 'En todos los pasajes', FALSE),
  (257, '¿A qué distancia mínima de un paso ferroviario a nivel se puede estacionar?', '100 metros', FALSE),
  (258, '¿A qué distancia mínima de un paso ferroviario a nivel se puede estacionar?', '10 metros', FALSE),
  (259, '¿A qué distancia mínima de un paso ferroviario a nivel se puede estacionar?', '50 metros', TRUE),
  (260, '¿A qué distancia mínima de un paso ferroviario a nivel se puede estacionar?', '5 metros', FALSE),
  (261, '¿A qué distancia de la entrada de una escuela, en horario de clase, está prohibido estacionar?', 'A menos de 10 metros a cada lado', TRUE),
  (262, '¿A qué distancia de la entrada de una escuela, en horario de clase, está prohibido estacionar?', 'A menos de 50 metros a cada lado', FALSE),
  (263, '¿A qué distancia de la entrada de una escuela, en horario de clase, está prohibido estacionar?', 'Solo frente a la puerta principal', FALSE),
  (264, '¿A qué distancia de la entrada de una escuela, en horario de clase, está prohibido estacionar?', 'No existe esa prohibición', FALSE),
  (265, '¿Cuánto tiempo puede permanecer un vehículo en un cajón azul?', 'Máximo 30 minutos, según la cartelería del lugar', TRUE),
  (266, '¿Cuánto tiempo puede permanecer un vehículo en un cajón azul?', 'Máximo 2 horas', FALSE),
  (267, '¿Cuánto tiempo puede permanecer un vehículo en un cajón azul?', 'Todo el día, si el vehículo es particular', FALSE),
  (268, '¿Cuánto tiempo puede permanecer un vehículo en un cajón azul?', 'Máximo 10 minutos', FALSE),
  (269, 'Al guardar el equipaje en el baúl, ¿qué conviene hacer con las piezas más pesadas?', 'Colocarlas arriba, para que no se mezclen con el equipaje liviano', FALSE),
  (270, 'Al guardar el equipaje en el baúl, ¿qué conviene hacer con las piezas más pesadas?', 'Colocarlas en el fondo del baúl, cerca del centro del vehículo', TRUE),
  (271, 'Al guardar el equipaje en el baúl, ¿qué conviene hacer con las piezas más pesadas?', 'Colocarlas en el asiento trasero', FALSE),
  (272, 'Al guardar el equipaje en el baúl, ¿qué conviene hacer con las piezas más pesadas?', 'Colocarlas en el portaequipajes sin sujetarlas', FALSE),
  (273, '¿En qué casos está permitida la marcha atrás en la Ciudad de Buenos Aires?', 'Para estacionar, para entrar o salir de un garaje y para salvar algún obstáculo', TRUE),
  (274, '¿En qué casos está permitida la marcha atrás en la Ciudad de Buenos Aires?', 'Solo para entrar a un garaje', FALSE),
  (275, '¿En qué casos está permitida la marcha atrás en la Ciudad de Buenos Aires?', 'Nunca, en ninguna circunstancia', FALSE),
  (276, '¿En qué casos está permitida la marcha atrás en la Ciudad de Buenos Aires?', 'Para superar un vehículo detenido', FALSE),
  (277, '¿Cuál es la función de los dibujos de un neumático en una calzada mojada?', 'Reducir el peso del vehículo', FALSE),
  (278, '¿Cuál es la función de los dibujos de un neumático en una calzada mojada?', 'Dar rigidez lateral al neumático', FALSE),
  (279, '¿Cuál es la función de los dibujos de un neumático en una calzada mojada?', 'Evacuar el agua de la zona de contacto para evitar el aquaplaning', TRUE),
  (280, '¿Cuál es la función de los dibujos de un neumático en una calzada mojada?', 'Aumentar la distancia de frenado', FALSE),
  (281, '¿Cuántos años de antigüedad desde su fabricación es aceptable como máximo para un neumático?', 'Más de 8 años, si el dibujo está bien', FALSE),
  (282, '¿Cuántos años de antigüedad desde su fabricación es aceptable como máximo para un neumático?', '5 años', TRUE),
  (283, '¿Cuántos años de antigüedad desde su fabricación es aceptable como máximo para un neumático?', '3 años', FALSE),
  (284, '¿Cuántos años de antigüedad desde su fabricación es aceptable como máximo para un neumático?', '10 años', FALSE),
  (285, '¿Qué efecto tiene tener los amortiguadores en mal estado sobre la frenada?', 'Aumenta la distancia de frenado alrededor de un 10%', TRUE),
  (286, '¿Qué efecto tiene tener los amortiguadores en mal estado sobre la frenada?', 'Reduce la distancia de frenado', FALSE),
  (287, '¿Qué efecto tiene tener los amortiguadores en mal estado sobre la frenada?', 'Solo afecta al confort de la suspensión', FALSE),
  (288, '¿Qué efecto tiene tener los amortiguadores en mal estado sobre la frenada?', 'Mejora la adherencia en la calzada mojada', FALSE),
  (289, '¿Cuál es la función del sistema ABS?', 'Bloquear las ruedas para que no patinen', FALSE),
  (290, '¿Cuál es la función del sistema ABS?', 'Evitar que las ruedas se bloqueen en una frenada brusca, liberando presión de frenado para recuperar adherencia', TRUE),
  (291, '¿Cuál es la función del sistema ABS?', 'Aumentar automáticamente la velocidad del vehículo', FALSE),
  (292, '¿Cuál es la función del sistema ABS?', 'Reducir el consumo de combustible', FALSE),
  (293, '¿Quiénes deben usar cinturón de seguridad dentro de un automóvil?', 'Solo quien conduce y el acompañante delantero', FALSE),
  (294, '¿Quiénes deben usar cinturón de seguridad dentro de un automóvil?', 'Solo las personas adultas', FALSE),
  (295, '¿Quiénes deben usar cinturón de seguridad dentro de un automóvil?', 'Todos los ocupantes, en los asientos delanteros y traseros', TRUE),
  (296, '¿Quiénes deben usar cinturón de seguridad dentro de un automóvil?', 'Solo los ocupantes que viajan en rutas', FALSE),
  (297, '¿Cómo debe estar colocado el apoyacabeza?', 'A la altura de los hombros', FALSE),
  (298, '¿Cómo debe estar colocado el apoyacabeza?', 'Inclinado hacia adelante, para apoyar la nuca', FALSE),
  (299, '¿Cómo debe estar colocado el apoyacabeza?', 'A la altura de la línea de los ojos en su parte central y con la parte más elevada a la altura superior de la cabeza', TRUE),
  (300, '¿Cómo debe estar colocado el apoyacabeza?', 'Solo a la altura de la nuca, sin ajuste', FALSE),
  (301, '¿Qué debe usar un niño o una niña que viaje en un automóvil, según la normativa de CABA?', 'Cinturón abdominal de dos puntos hasta cumplir 8 años', FALSE),
  (302, '¿Qué debe usar un niño o una niña que viaje en un automóvil, según la normativa de CABA?', 'El cinturón del asiento delantero si viaja con un adulto', FALSE),
  (303, '¿Qué debe usar un niño o una niña que viaje en un automóvil, según la normativa de CABA?', 'El asiento delantero con airbag desactivado', FALSE),
  (304, '¿Qué debe usar un niño o una niña que viaje en un automóvil, según la normativa de CABA?', 'Un sistema de sujeción hasta los 12 años, o mientras mida menos de 1,50 m o pese menos de 36 kg', TRUE),
  (305, '¿Cuál es la distancia lateral mínima recomendada al sobrepasar un ciclista?', '1 metro', FALSE),
  (306, '¿Cuál es la distancia lateral mínima recomendada al sobrepasar un ciclista?', '1,5 metros', TRUE),
  (307, '¿Cuál es la distancia lateral mínima recomendada al sobrepasar un ciclista?', '3 metros', FALSE),
  (308, '¿Cuál es la distancia lateral mínima recomendada al sobrepasar un ciclista?', '5 metros', FALSE),
  (309, '¿Cuál es la potencia máxima del motor de un monopatín eléctrico?', '250 W', FALSE),
  (310, '¿Cuál es la potencia máxima del motor de un monopatín eléctrico?', '1500 W', FALSE),
  (311, '¿Cuál es la potencia máxima del motor de un monopatín eléctrico?', '500 W', TRUE),
  (312, '¿Cuál es la potencia máxima del motor de un monopatín eléctrico?', '1200 W', FALSE),
  (313, '¿Cuál es la velocidad máxima de una bicicleta con asistencia eléctrica?', '20 km/h', FALSE),
  (314, '¿Cuál es la velocidad máxima de una bicicleta con asistencia eléctrica?', '30 km/h', FALSE),
  (315, '¿Cuál es la velocidad máxima de una bicicleta con asistencia eléctrica?', '45 km/h', FALSE),
  (316, '¿Cuál es la velocidad máxima de una bicicleta con asistencia eléctrica?', '25 km/h', TRUE),
  (317, '¿Cuál es la edad mínima para conducir una bicicleta con asistencia eléctrica o un monopatín eléctrico?', '14 años', FALSE),
  (318, '¿Cuál es la edad mínima para conducir una bicicleta con asistencia eléctrica o un monopatín eléctrico?', '15 años', FALSE),
  (319, '¿Cuál es la edad mínima para conducir una bicicleta con asistencia eléctrica o un monopatín eléctrico?', '18 años', FALSE),
  (320, '¿Cuál es la edad mínima para conducir una bicicleta con asistencia eléctrica o un monopatín eléctrico?', '16 años', TRUE)
) AS v(ord, question, answer, iscorrect)
JOIN hard_questions q ON q.question = v.question
ORDER BY v.ord;

COMMIT;
